(() => {
  const profiles = (window.PROFILES || []).map(p => ({...p, price: Number(p.price_from_kzt), categories: p.categories.split('|'), formats: p.event_formats.split('|'), languages: p.languages.split('|'), busy: p.busy_dates ? p.busy_dates.split('|') : []}));
  const categories = [...new Set(profiles.flatMap(p => p.categories))].sort((a,b) => a.localeCompare(b,'ru'));
  const $ = id => document.getElementById(id);
  const money = n => `${Number(n).toLocaleString('ru-RU')} ₸`;
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeText = (s, n=180) => {const t=String(s||'').replace(/\s+/g,' ').trim(); return t.length>n ? t.slice(0,n).trimEnd()+'…' : t;};
  const firstLetter = s => [...s][0] || 'П';
  const avatarColors = ['#d7e6dc','#f0d7c8','#e4d8ee','#dce5ef','#f0e5bd','#ead5d9'];
  const titleCase = s => s.charAt(0).toUpperCase()+s.slice(1);
  const placeholderDate = new Date().toISOString().slice(0,10);
  $('date').value = placeholderDate < '2026-09-23' ? '2026-10-15' : placeholderDate > '2026-12-31' ? '2026-10-15' : placeholderDate;
  $('navCount').textContent = profiles.length; $('catalogCount').textContent = profiles.length;
  categories.forEach(c => { $('category').add(new Option(SiteI18n.category(c),c)); $('catalogCategory').add(new Option(SiteI18n.category(c),c)); });
  function translateOptions(){for(const s of ['city','catalogCity'])for(const o of $(s).options)if(o.value)o.textContent=SiteI18n.city(o.value);for(const s of ['format'])for(const o of $(s).options)o.textContent=SiteI18n.format(o.value);for(const o of $('language').options)o.textContent=o.value?SiteI18n.language(o.value):SiteI18n.tr('Любой язык');for(const s of ['category','catalogCategory'])for(const o of $(s).options)if(o.value)o.textContent=SiteI18n.category(o.value);}

  // Persisted visual preferences apply sitewide.
  const prefs = (() => {try{return JSON.parse(localStorage.getItem('eventPrefs')||'{}')}catch{return {}}})();
  let fontScale = Math.min(1.2,Math.max(.9,Number(prefs.fontScale)||1));
  function setPrefs(){document.documentElement.dataset.theme=prefs.theme||'light';document.documentElement.dataset.contrast=prefs.contrast?'on':'off';document.documentElement.style.setProperty('--font-scale',fontScale);$('themeToggle').textContent=prefs.theme==='dark'?'☀':'☾';$('themeToggle').setAttribute('aria-label',SiteI18n.tr(prefs.theme==='dark'?'Включить дневной режим':'Включить ночной режим'));$('contrastToggle').setAttribute('aria-pressed',String(Boolean(prefs.contrast)));localStorage.setItem('eventPrefs',JSON.stringify({...prefs,fontScale}));}
  setPrefs();
  SiteI18n.set(SiteI18n.lang);translateOptions();
  $('fontUp').addEventListener('click',()=>{fontScale=Math.min(1.3,+(fontScale+.05).toFixed(2));setPrefs()}); $('fontDown').addEventListener('click',()=>{fontScale=Math.max(.85,+(fontScale-.05).toFixed(2));setPrefs()});
  $('themeToggle').addEventListener('click',()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';setPrefs()}); $('contrastToggle').addEventListener('click',()=>{prefs.contrast=!prefs.contrast;setPrefs()});
  let lastQuery=null;
  $('languageSwitch').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;SiteI18n.set(b.dataset.lang);setPrefs();translateOptions();renderCatalog();if(lastQuery)renderResults(findMatches(lastQuery),lastQuery);});

  const tr=SiteI18n.tr, msg=SiteI18n.message;
  function scoreCandidate(p,q){
    const reasons=[]; let score=0;
    const room=p.categories.some(c=>c==='Банкетный зал'||c==='Загородная площадка'||c==='Отель'||c==='Ресторан');
    if(p.price<=q.budget){score+=30;const ratio=p.price/q.budget; reasons.push(msg('reason',ratio<=.65?0:1,money(p.price),money(q.budget)))}
    if(p.formats.includes(q.format)){score+=24; reasons.push(msg('reason',2,SiteI18n.format(q.format)))}
    if(q.language){if(p.languages.includes(q.language)){score+=18;reasons.push(msg('reason',3,SiteI18n.language(q.language)))}else return null}
    if(q.hours && !room && p.max_hours){if(p.max_hours>=q.hours){score+=12;reasons.push(msg('reason',4,p.max_hours,q.hours))}else return null}
    else if(q.hours&&!room&&!p.max_hours){score+=4;reasons.push(msg('reason',5))}
    const words=q.format==='свадьба'||q.format==='той'?['свадеб','той','торжеств','гост']:q.format==='корпоратив'?['корпорат','бизнес','компан','форум']:q.format==='конференция'?['конференц','форум','делов','бизнес']:q.format==='юбилей'?['юбиле','торжеств','вечер']:['день рожд','праздник','вечер'];
    const desc=p.description.toLowerCase(); const hit=words.find(w=>desc.includes(w));
    if(hit){score+=8;reasons.push(msg('reason',6,hit.replace(/\.$/,'')))}
    if(!reasons.length) reasons.push(msg('reason',7,SiteI18n.category(p.categories.find(c=>c===q.category))));
    if(p.price_imputed==='True' && reasons.length<2) reasons.push(msg('reason',8));
    return {p,score,reasons:reasons.slice(0,2)};
  }

  function findMatches(q){
    const inCity=profiles.filter(p=>p.city===q.city&&p.categories.includes(q.category));
    if(!inCity.length)return {kind:'missing',inCity,total:0,matches:[]};
    const available=inCity.filter(p=>!p.busy.includes(q.date));
    const eligible=available.map(p=>scoreCandidate(p,q)).filter(Boolean);
    eligible.sort((a,b)=>b.score-a.score || a.p.price-b.p.price || a.p.id.localeCompare(b.p.id));
    if(!eligible.length)return {kind:'empty',inCity,total:0,matches:[],busy:inCity.filter(p=>p.busy.includes(q.date)).length,available:available.length};
    return {kind:'success',inCity,total:eligible.length,matches:eligible.slice(0,3),eligibleCount:eligible.length,available:available.length};
  }
  function renderResults(result,q){
    const root=$('results'); root.className='results is-visible';
    const lng=SiteI18n.lang, locale=lng==='ru'?'ru-RU':lng==='kk'?'kk-KZ':'en-US';
    if(result.kind==='missing'){const count=profiles.filter(p=>p.categories.includes(q.category)).length;root.innerHTML=`<div class="result-banner result-empty"><div class="result-icon">⌕</div><div><span class="result-kicker">${msg('missing',0)}</span><h3>${msg('missing',1,esc(SiteI18n.city(q.city)),esc(SiteI18n.category(q.category)))}</h3><p>${msg('missing',2,count)}</p></div></div>`;return;}
    if(result.kind==='empty'){let reasons=[];if(result.busy){const booked=result.busy===1?msg('empty',2):result.busy<5?msg('empty',3):msg('empty',4);reasons.push(`${result.busy} ${booked} ${new Date(q.date+'T12:00:00').toLocaleDateString(locale,{day:'numeric',month:'long'})}`)}if(result.available<result.inCity.length)reasons.push(msg('empty',5));reasons.push(msg('empty',6));root.innerHTML=`<div class="result-banner result-empty"><div class="result-icon">○</div><div><span class="result-kicker">${msg('empty',0)}</span><h3>${msg('empty',1,result.inCity.length,esc(SiteI18n.category(q.category)),esc(SiteI18n.city(q.city)))}</h3><p>${reasons.map(esc).join('; ')}. ${msg('empty',7)}</p></div></div>`;return;}
    const d=new Date(q.date+'T12:00:00').toLocaleDateString(locale,{day:'numeric',month:'long',year:'numeric'});const noun=result.eligibleCount===1?msg('successTitle',1):result.eligibleCount<5?msg('successTitle',2):msg('successTitle',3);const tail=result.eligibleCount>3?msg('onlyThree',0):'';
    root.innerHTML=`<div class="results-heading"><div><span class="result-kicker">${msg('resultKicker',0)} · ${esc(SiteI18n.city(q.city).toUpperCase())} · ${esc(d.toUpperCase())}</span><h3>${msg('successTitle',0,result.eligibleCount,noun,tail)}</h3></div><span class="results-count">${result.matches.length} / 3</span></div><div class="match-grid">${result.matches.map((m,i)=>matchCard(m,i,q)).join('')}</div>`;
    root.querySelectorAll('[data-profile]').forEach(btn=>btn.addEventListener('click',()=>openProfile(btn.dataset.profile)));
  }
  function matchCard(m,i,q){const p=m.p;const sourceFlag=p.synthetic==='True'?msg('resultKicker',2):p.price_imputed==='True'?msg('resultKicker',1):'';return `<article class="match-card"><div class="match-top"><span class="match-rank">0${i+1} <i>${msg('onlyThree',1)}</i></span><span class="availability"><b></b> ${msg('onlyThree',2)}</span></div><div class="match-identity"><div class="avatar avatar-${i}" aria-hidden="true">${esc(firstLetter(p.anon_name))}<span class="avatar-star">✳</span></div><div><span class="match-category">${esc(p.categories.map(SiteI18n.category).join(' · '))}</span><h4>${esc(p.anon_name)}</h4><span class="match-place">${esc(SiteI18n.city(p.city))} <span>·</span> ${tr('от')} ${money(p.price)}</span>${sourceFlag?`<span class="source-flag">${esc(sourceFlag)}</span>`:''}</div></div><div class="explanation"><span class="explanation-label">${msg('onlyThree',3)}</span><p>${m.reasons.map(esc).join(' ')}</p></div><div class="match-meta">${p.languages.map(l=>`<span>${esc(SiteI18n.language(l))}</span>`).join('')} ${p.max_hours?`<span>${tr('до')} ${p.max_hours} ${SiteI18n.lang==='en'?'h':'ч'}</span>`:`<span>${tr('без лимита часов')}</span>`}</div><button class="profile-link" data-profile="${esc(p.id)}" type="button">${msg('onlyThree',4)} <span>↗</span></button></article>`}
  $('matchForm').addEventListener('submit',e=>{e.preventDefault();$('formError').hidden=true;if(!$('matchForm').reportValidity())return;const q={city:$('city').value,date:$('date').value,format:$('format').value,category:$('category').value,budget:Number($('budget').value),hours:$('hours').value?Number($('hours').value):null,language:$('language').value};if(q.date<'2026-09-23'||q.date>'2026-12-31'){$('formError').textContent=msg('misc',0);$('formError').hidden=false;return;}lastQuery=q;renderResults(findMatches(q),q);$('results').scrollIntoView({behavior:'smooth',block:'start'});});

  function profileCard(p,i){const cats=p.categories.map(c=>`<span class="tag">${esc(SiteI18n.category(c))}</span>`).join('');const provenance=p.synthetic==='True'?msg('misc',9):p.price_imputed==='True'||p.city_imputed==='True'?msg('misc',8):'';const descOrigin=SiteI18n.lang==='en'?'Description · original Russian':SiteI18n.lang==='kk'?'Сипаттама · түпнұсқасы орысша':'Описание · оригинал на русском';return `<article class="profile-card"><button type="button" class="profile-open" data-profile="${esc(p.id)}" aria-label="${tr('Открыть анкету')} ${esc(p.anon_name)}"><div class="portfolio-art portfolio-${i%6}"><span class="portfolio-label">${msg('misc',6)}</span><span class="portfolio-symbol">${['✳','❋','✦','❀','◉','✷'][i%6]}</span><span class="portfolio-id">${esc(p.id)}</span></div><div class="profile-info"><div class="profile-tags">${cats}${provenance?`<span class="tag provenance-tag">${esc(provenance)}</span>`:''}</div><h3>${esc(p.anon_name)}</h3><div class="profile-location">${esc(SiteI18n.city(p.city))} <span>·</span> ${tr('от')} ${money(p.price)}</div><p>${esc(safeText(p.description,118))}</p><span class="description-origin-card">${descOrigin}</span><div class="profile-bottom"><span>${esc(p.languages.map(SiteI18n.language).join(' · '))}</span><b>${msg('misc',7)}</b></div></div></button></article>`}
  function renderCatalog(){const search=$('searchProfiles').value.trim().toLocaleLowerCase('ru');const cat=$('catalogCategory').value;const city=$('catalogCity').value;const shown=profiles.filter(p=>(!cat||p.categories.includes(cat))&&(!city||p.city===city)&&(!search||[p.anon_name,p.description,p.city,p.categories.join(' ')].join(' ').toLocaleLowerCase('ru').includes(search)));$('profileGrid').innerHTML=shown.map((p,i)=>profileCard(p,i)).join('');const n=shown.length, noun=n===1?msg('misc',3):msg('misc',2);$('catalogTotal').textContent=`${n} ${noun}`;$('emptyCatalog').textContent=msg('misc',5);$('emptyCatalog').hidden=shown.length!==0;$('profileGrid').querySelectorAll('[data-profile]').forEach(btn=>btn.addEventListener('click',()=>openProfile(btn.dataset.profile)));}
  ['searchProfiles','catalogCategory','catalogCity'].forEach(id=>$(id).addEventListener('input',renderCatalog));renderCatalog();
  function openProfile(id){const p=profiles.find(x=>x.id===id);if(!p)return;const d=$('dialogContent');const locale=SiteI18n.lang==='ru'?'ru-RU':SiteI18n.lang==='kk'?'kk-KZ':'en-US';const busyMonths=[...new Set(p.busy.map(x=>new Date(x+'T12:00:00').toLocaleDateString(locale,{month:'long'})))];const provenance=[p.synthetic==='True'?msg('misc',9):null,p.city_imputed==='True'?(SiteI18n.lang==='en'?'Estimated city':SiteI18n.lang==='kk'?'Қала бағалау мәні':'Город оценочный'):null,p.price_imputed==='True'?(SiteI18n.lang==='en'?'Estimated price':SiteI18n.lang==='kk'?'Баға бағалау мәні':'Цена оценочная'):null].filter(Boolean).join(' · ');d.innerHTML=`<div class="dialog-art portfolio-${profiles.indexOf(p)%6}"><span class="portfolio-label">${SiteI18n.lang==='en'?'PORTFOLIO · ILLUSTRATION':SiteI18n.lang==='kk'?'ПОРТФОЛИО · СУРЕТТЕМЕ':'ПОРТФОЛИО · ИЛЛЮСТРАЦИЯ'}</span><span class="dialog-art-mark">${esc(firstLetter(p.anon_name))}</span></div><div class="dialog-body"><span class="result-kicker">${esc(p.categories.map(SiteI18n.category).join(' · ').toUpperCase())} · ${esc(SiteI18n.city(p.city).toUpperCase())}</span><h2>${esc(p.anon_name)}</h2><div class="dialog-price">${tr('от')} ${money(p.price)} <small>${SiteI18n.lang==='en'?'per event':SiteI18n.lang==='kk'?'іс-шара үшін':'за мероприятие'}</small></div><p class="description-origin">${SiteI18n.lang==='en'?'Original vendor description · Russian':SiteI18n.lang==='kk'?'Мердігер сипаттамасының түпнұсқасы · орысша':'Оригинал описания подрядчика · русский'}</p><p class="dialog-description">${esc(p.description)}</p><div class="dialog-facts"><div><small>${tr('ФОРМАТЫ')}</small><b>${esc(p.formats.map(SiteI18n.format).join(' · '))}</b></div><div><small>${tr('ЯЗЫКИ')}</small><b>${esc(p.languages.map(SiteI18n.language).join(' · '))}</b></div><div><small>${tr('ДЛИТЕЛЬНОСТЬ')}</small><b>${p.max_hours?`${tr('до')} ${p.max_hours} ${SiteI18n.lang==='en'?'hours':'ч.'}`:(SiteI18n.lang==='en'?'not tied to on-site hours':SiteI18n.lang==='kk'?'алаңда болу уақытына тәуелді емес':'не зависит от часов на площадке')}</b></div><div><small>${tr('КАЛЕНДАРЬ')}</small><b>${p.busy.length} ${tr('занятых дней')}${busyMonths.length?` · ${esc(busyMonths.join(', '))}`:''}</b></div></div><p class="demo-note">${provenance?`${esc(provenance)}. `:''}${msg('misc',10)}</p></div>`;$('profileDialog').showModal();}
  $('profileDialog').querySelector('.dialog-close').addEventListener('click',()=>$('profileDialog').close());$('profileDialog').addEventListener('click',e=>{if(e.target===$('profileDialog'))$('profileDialog').close()});
})();
